services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: my_django_app_dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mount the local code into the container for live updates
    env_file:
      - ovalie/.env  # Use a separate .env file for dev settings
    environment:
      DJANGO_SETTINGS_MODULE: ovalie.settings.dev  # Ensure dev settings are used
    command: python -m ovalie.manage runserver 0.0.0.0:8000  # Start Django dev server

  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: my_django_worker_dev
    command: bash -c "python -m ovalie.manage qcluster"  # Use a dev-specific command if needed
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    env_file:
      - ovalie/.env
