services:
  web:
    build: .
    container_name: my_django_app
    ports:
      - "8000:8000"
    volumes:
      - ./ovalie/db.sqlite3:/app/db.sqlite3

  worker:
    build: .
    command: bash -c "python ovalie/manage.py qcluster"
    volumes:
      - ./ovalie/db.sqlite3:/app/db.sqlite3
