services:
  web:
    build: .
    container_name: my_django_app
    ports:
      - "8000:8000"
    volumes:
      - djangoin_cleats_django_db:/app/db.sqlite3
    env_file:
      - ovalie/.env
  worker:
    build: .
    command: bash -c "python ovalie/manage.py qcluster"
    volumes:
      - djangoin_cleats_django_db:/app/db.sqlite3

volumes:
  djangoin_cleats_django_db: