services:
  web:
    build: .
    container_name: my_django_app
    ports:
      - "8000:8000"
    volumes:
      - /root/database/db.sqlite3:/app/db.sqlite3
      - /root/media:/app/ovalie/news/media/images
    env_file:
      - ovalie/.env

  worker:
    build: .
    container_name: djangoincleats_worker
    command: bash -c "python ovalie/manage.py qcluster"
    volumes:
      - /root/database/db.sqlite3:/app/db.sqlite3
    env_file:
      - ovalie/.env
