services:
  web:
    build: .
    container_name: my_django_app
    ports:
      - "8000:8000"
    volumes:
      - django_db:/app/db.sqlite3
    env_file:
      - ovalie/.env

  worker:
    build: .
    container_name: djangoincleats_worker
    command: bash -c "python ovalie/manage.py qcluster"
    volumes:
      - django_db:/app/db.sqlite3
    env_file:
      - ovalie/.env

volumes:
  django_db:
    name: django_db
