services:
  web:
    build: .
    container_name: my_django_app
    ports:
      - "8000:8000"
    volumes:
      - /root/database/db.sqlite3:/app/db.sqlite3
      - /var/www/paparugby/media:/app/ovalie/news/media
      - /var/www/paparugby/staticfiles:/app/staticfiles
    env_file:
      - ovalie/.env
    environment:
      DJANGO_SETTINGS_MODULE: ovalie.settings.settings

  worker:
    build: .
    container_name: djangoincleats_worker
    command: bash -c "python -m ovalie.manage qcluster"
    volumes:
      - /root/database/db.sqlite3:/app/db.sqlite3
    env_file:
      - ovalie/.env
