# Generated by Django 5.1.2 on 2024-12-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='admin_comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
