# Generated by Django 5.1.4 on 2024-12-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
