# Generated by Django 5.1.4 on 2024-12-11 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.website'),
        ),
    ]
