# Generated by Django 5.1.4 on 2024-12-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_website_alter_article_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/news/images/keywords_images')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='static/news/article_image'),
        ),
        migrations.AlterField(
            model_name='website',
            name='logo',
            field=models.ImageField(upload_to='static/news/images/logos/'),
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='news.keyword'),
        ),
    ]
