# Generated by Django 5.1.4 on 2024-12-18 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_keyword_alter_article_image_alter_website_logo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keyword',
            new_name='KeywordGroup',
        ),
    ]
