# Generated by Django 5.1.4 on 2024-12-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_rename_keyword_keywordgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordgroup',
            name='keywords',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
