# Generated by Django 5.1.4 on 2024-12-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_keywordgroup_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordgroup',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
