# Generated by Django 5.1.4 on 2024-12-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_article_is_french_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
    ]
