# Generated by Django 5.1.4 on 2024-12-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_article_is_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(unique=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('is_visible', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
