# Generated by Django 5.1.4 on 2025-01-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='banner',
            field=models.ImageField(null=True, upload_to='static/news/images/banners/'),
        ),
    ]
