# Generated by Django 5.1.4 on 2025-01-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_videos_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='channel',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
