# Generated by Django 5.1.4 on 2025-01-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_videos_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
