# Generated by Django 5.1.4 on 2025-01-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_alter_videos_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordgroup',
            name='league',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
