# Generated by Django 5.1.4 on 2025-01-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_game_delete_games'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='away_team',
            new_name='away_team_name',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='home_team',
            new_name='home_team_name',
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('league', 'round_number', 'home_team_name', 'away_team_name')},
        ),
        migrations.AddField(
            model_name='game',
            name='away_team_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='game_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='home_team_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='round_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
