# Generated by Django 5.1.4 on 2025-01-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_rename_away_team_game_away_team_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
