# Generated by Django 5.1.4 on 2025-01-16 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_alter_game_start_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set(),
        ),
    ]
