# Generated by Django 5.1.4 on 2025-02-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0027_article_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='with_picture',
            field=models.BooleanField(default=False),
        ),
    ]
