# Generated by Django 5.1.4 on 2025-02-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_article_with_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='papa_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
